### PR TITLE
Add an icon and link for OrganizationMembers

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add an icon and link to the Project organization for Members of the project
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes 
| How to test?      | Check if an icon is visible for project members.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

Screenshot (22)

Screenshot (23)

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Hello

The code seems valid but... what is the goal of the PR? What is the benefit to show "who is a project member" and "who is not"

I'm worried it will actually create a jealousy feeling between project members and not-project members 😅 like "we want to show off". And I don't see what value it brings to the people visiting the webpage 🤔

**Comment by Progi1984** [comment]
@coffrep I ping you as you are the PM on this project. What do you think of the PR of @okom3pom ?

**Comment by okom3pom** [comment]
I find it interesting to find the project members easily in this list. 

I also think that visitors will click on the links and for example find out that they can become a commiter or other.

This will put the project in the spotlight and why not recruit more members.

For example, seeing the empty committer section made me want to join.

**Comment by NeOMakinG** [comment]
> Hello
> 
> The code seems valid but... what is the goal of the PR? What is the benefit to show "who is a project member" and "who is not"
> 
> I'm worried it will actually create a jealousy feeling between project members and not-project members 😅 like "we want to show off". And I don't see what value it brings to the people visiting the webpage 🤔

No need to be jealous, join the Organization as a maintainer/committer if you are involved!

By the way, I would call it `Organization Member` as it's more global than `Project` which basically means only one project don't you think?

**Comment by okom3pom** [comment]
Why not add links to the site like this:

Screenshot (26)

**Comment by coffrep** [comment]
Hi everyone, thanks for the ping Progi1984! I'm approving of this PR, thanks okom3pom for creating it, and I'm also understanding there is another PR that's created to fix the missing popup when clicking on a contributor's profile: if this PR could also be merged it would be great. Let me know if you need additional feedback.

**Comment by matks** [comment]
> For example, seeing the empty committer section made me want to join.

Nice point 👍 thanks for the answer

**Comment by matks** [comment]
@NeOMakinG can you validate the frontend?

**Comment by okom3pom** [comment]
@coffrep the other PR is merged it is necessary to wait for the new version of the site.

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @coffrep & @okom3pom

**Pull request merged**
